
name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Pull swe-agent docker container
        run: |
          docker pull sweagent/swe-agent:latest
      - name: Create keys.cfg
        run: |
          touch keys.cfg
      - name: Install dependencies
        run: |
            pip install .
            pip install pytest pytest-cov
      - name: Run pytest
        run: |
            pytest --cov
      - name: Explicitly convert coverage to xml
        run: coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: princeton-nlp/SWE-agent